language: node_js
node_js:
- '4'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
- npm install hexo --save
script:
- hexo clean
- hexo g

after_success:
- hexo deploy
